### ISSUE TITLE
[BUG]: alias commadn nto working

### ISSUE THREAD

**Issue by shehrozeee** [github/gh-copilot#52] opened 2024-03-23 09:30 UTC
### What happened?
installed gh copilot cli and wanted to setup alias,
used the 
$GH_COPILOT_PROFILE = Join-Path -Path $(Split-Path -Path $PROFILE -Parent) -ChildPath "gh-copilot.ps1"
gh copilot alias -- pwsh | Out-File ( New-Item -Path $GH_COPILOT_PROFILE -Force )
echo ". $GH_COPILOT_PROFILE" >> $PROFILE
to setup alias as mentioned on the readme.

The alias is not configured and I now get an error when I open a new powershell
![image](https://github.com/github/gh-copilot/assets/33824420/756df7a3-c168-4374-bae7-bc4db0fa2135)

I have checked the brackets in the gh-copilot.ps1 and they seem to be fine according to vs code syntax highlighting at least.

just to check, I copied the functions from the file and pasted them in powershell manually, it stops parsing before the last } and throws the same error

![image](https://github.com/github/gh-copilot/assets/33824420/b0fd3769-f36a-41f5-8fe4-032060c041f4)

### Versions
PS C:\Users\Shehroze> gh version
gh version 2.46.0 (2024-03-20)
https://github.com/cli/cli/releases/tag/v2.46.0

### Relevant terminal output
PS C:\Users\Shehroze> function ghcs {
>> # Debug support provided by common PowerShell function parameters, which is natively aliased as -d or -db
>> # https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.4#-debug
>> param(
>> [ValidateSet('gh', 'git', 'shell')]
>> [Alias('t')]
>> [String]$Target = 'shell',
>>
>> [Parameter(Position=0, ValueFromRemainingArguments)]
>> [string]$Prompt
>> )
>> begin {
>> # Create temporary file to store potential command user wants to execute when exiting
>> $executeCommandFile = New-TemporaryFile
>>
>> # Store original value of GH_DEBUG environment variable
>> $envGhDebug = $Env:GH_DEBUG
>> }
>> process {
>> if ($PSBoundParameters['Debug']) {
>> $Env:GH_DEBUG = 'api'
>> }
>>
>> gh copilot suggest -t $Target -s "$executeCommandFile" $Prompt
>> }
>> end {
>> # Execute command contained within temporary file if it is not empty
>> if ($executeCommandFile.Length -gt 0) {
>> # Extract command to execute from temporary file
>> $executeCommand = (Get-Content -Path $executeCommandFile -Raw).Trim()
>>
>> # Insert command into PowerShell up/down arrow key history
>> [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($executeCommand)
>>
>> # Insert command into PowerShell history
>> $now = Get-Date
>> $executeCommandHistoryItem = [PSCustomObject]@{
>> CommandLine = $executeCommand
>> ExecutionStatus = [Management.Automation.Runspaces.PipelineState]::NotStarted
>> StartExecutionTime = $now
>> EndExecutionTime = $now.AddSeconds(1)
>> }
>> Add-History -InputObject $executeCommandHistoryItem
>>
>> # Execute command
>> Write-Host "`n"
>> Invoke-Expression $executeCommand
>> }
>> }
>> clean {
>> # Clean up temporary file used to store potential command user wants to execute when exiting
>> Remove-Item -Path $executeCommandFile
>>
>> # Restore GH_DEBUG environment variable to its original value
>> $Env:GH_DEBUG = $envGhDebug
>> }
At line:1 char:15
+ function ghcs {
+               ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

PS C:\Users\Shehroze> }
At line:1 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

on opening a new powershell->

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

At C:\Users\Shehroze\OneDrive\Documents\WindowsPowerShell\gh-copilot.ps1:8 char:15
+ function ghcs {
+               ~
Missing closing '}' in statement block or type definition.
At C:\Users\Shehroze\OneDrive\Documents\WindowsPowerShell\gh-copilot.ps1:64 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
At C:\Users\Shehroze\OneDrive\Documents\WindowsPowerShell\gh-copilot.ps1:66 char:15
+ function ghce {
+               ~
Missing closing '}' in statement block or type definition.
At C:\Users\Shehroze\OneDrive\Documents\WindowsPowerShell\gh-copilot.ps1:88 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

PS C:\Users\Shehroze>

**Comment by andyfeller** [comment] 2024-03-24 00:33
@shehrozeee : thank you for opening the issue and my apologies for the confusion!

I believe you're running into the problem described in #38 as the current PowerShell is 7.4+ and you are using PowerShell Desktop 5.x

I'm going to close this as a duplicate of #50 for now.

**Closed** 2024-03-24 00:34 UTC
Labels: bug, needs-triage
