### ISSUE TITLE
[FEAT]: Command-line Chat Features

### ISSUE THREAD

**Issue by invisible-gaopg** [github/gh-copilot#102] opened 2024-11-06 01:54 UTC
### Chat in the Command Line
When working with Bash, sometimes I need more features than simply explaining commands. Sometimes I may want to ask "I have the task xxx, how to use commands to do this? Please write a list of operations for me". without opening VSCode. So is there any way to chat in the command line?

**Comment by williammartin** [comment] 2024-11-06 12:29
Hey @invisible-gaopg,

Currently there is no way to chat with copilot on the command line, it's generally something we're interested in but have not prioritised the work for.

Closing this as a duplicate of https://github.com/github/gh-copilot/issues/36

Cheers!

**Closed by williammartin** 2024-11-06 12:29 UTC
Labels: enhancement, needs-triage
