### ISSUE TITLE
[BUG]: Add distro to context

### ISSUE THREAD

**Issue by Jak2k** [github/gh-copilot#22] opened 2023-12-14 20:09 UTC
## What happened?
_What did you do? What happened? What did you expect to happen?_ Copilot gave me a command that works on another distro, but not on mine.

## Solution
Add the distro to the internal AI promt.

**Comment by andyfeller** [comment] 2024-01-12 20:24
@jak2k: Thank you for opening up this issue!  I'm going to close this as it is a duplicate of #8 where deeper conversation is going on.

**Closed by andyfeller** 2024-01-12 20:24 UTC
Labels: bug, needs-triage
