### ISSUE TITLE
Support android-arm`

### ISSUE THREAD

**Issue by kelexine** [github/gh-copilot#53] opened 2024-03-23 13:49 UTC
Thanks for taking the time to fill out this out! :bow:
By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/gh-copilot/blob/main/CODE_OF_CONDUCT.md).

### Describe the need
_What problem are you trying to solve? What do you want to happen?_

### Version
_Do these docs apply to a specific version?_
_For example: `gh-copilot v0.5.2-beta`_

### Relevant terminal output
_Please copy and paste any relevant terminal output._
_Please check your output before submission to ensure sensitive information is redacted._

**Comment by KayllonDouglas** [comment] 2024-03-23 15:31
Duplicate of #30

**Comment by kelexine** [comment] 2024-03-23 17:24
My bad, but as in #30 when am not at home, which is most of the times, I work with my android phone, so it would be nice to make it work on android

**Closed** 2024-03-23 17:25 UTC
Labels: enhancement, needs-triage
